### ISSUE TITLE
Incompatible with Secret Rooms

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [ThePoultryMan/Lanterns-Belong-On-Walls#1]
**MC** 1.18.2
**Fabric API** 0.51.1
**[Secret Rooms](https://www.curseforge.com/minecraft/mc-mods/secret-rooms-fabric)** 1.3.1
**Lanterns** 1.0.1

When both mods are installed together, the game crashes on startup: https://gist.github.com/Footage2-Amply-Pounce/f50b7fe9f28653957c57e7bce363c0a6

**Comment by ThePoultryMan** [comment]
The game was crashing due to the properties not being added in the `appendProperties()` method. I fixed this with a simple mixin into `LanternButtonBlock`. However, the models still need to be fixed. All these changes are being made on the [bug/secretrooms](https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/tree/bug/secretrooms) branch.

**Comment by ThePoultryMan** [comment]
Update: These changes have been pushed to [1.18.x/dev](https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/tree/1.18.x/dev), but I have discovered a new bug that I need to fix before I release another update.

_Unrelated to the bug above_: My current implantation requires the player to use a bundled resource pack that overrides the blockstate models from Secret Rooms. This causes the issue that players who don't enable the pack know which lanterns are the secret buttons. I'll play around to see if I can fix this, but it might be a permanent issue.

**Comment by Footage2-Amply-Pounce** [comment]
Thanks for the update. The resource pack thing won't be an issue for me personally, I mostly play alone. But, of course, if you can fix it, that'd be great.

**Comment by ThePoultryMan** [comment]
The resource pack issue has been somewhat solved. If Secret Rooms is detected on launch, the resource pack will be forced on, but if it is not, then the resource pack will behave normally. I'm assuming that this detection is based on the order that mods are loaded, so if Lanterns Belong on Walls is loaded before Secret Rooms, then it won't work. However, this is most likely a good enough solution.

The action build that contains these changes is [here](https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/actions/runs/2309616797). Before I release another update, I'm going to see if I can fix #2.
