### ISSUE TITLE
Lantern States Broken After Launching With Mod

### ISSUE THREAD

**Issue by Psychodeus** [ThePoultryMan/Lanterns-Belong-On-Walls#11]
## **Describe the bug**
It happened when I already have lantern in my world and then install your mod. It just happened to all my lantern unless I destroy and place it again.

## **Screenshots**
![2022-10-16_01 57 19](https://user-images.githubusercontent.com/93028949/196001350-b7210755-9ea9-4730-83e8-4883e5aafc58.png)
![2022-10-16_01 57 35](https://user-images.githubusercontent.com/93028949/196001354-b9c474d3-41fe-4f2a-93ea-c6deff8da0ff.png)
It appear to be like this. Most of the time it appears only hitbox, but some place it also appear physically, even tho in that case it doesn't even attached to the wall (placed on the ground) and yet form as it identify as hangging on the wall.

## **Mod Information:**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer
Mod version: 1.4

## **Logs**
I... I forgot which one, it was few days ago and I let this little bug there.

**Comment by ThePoultryMan** [comment]
Tested with 1.6.0, and this no longer happens.
