### ISSUE TITLE
Extended Copper Mod Support

### ISSUE THREAD

**Issue by NealSavage** [ThePoultryMan/Lanterns-Belong-On-Walls#16]
Hey, could we get support for the Extended Copper mod? Right now it just does this. 
![2023-02-15_19 27 27](https://user-images.githubusercontent.com/4138801/219260838-9a9e1886-8111-47c1-9adc-315e774af1a5.png)
If I put my cursor on it, I do get an outline, but there's no.... item. 
![2023-02-15_19 30 55](https://user-images.githubusercontent.com/4138801/219261401-f075b2c2-c8f5-42a7-b0c2-11215e4f8f31.png)

https://beta.curseforge.com/minecraft/mc-mods/expanded-copper Here's a link to their mod, to help you find it. 

Let me know, would love the copper lantern on the wall there! Thanks.

**Comment by ThePoultryMan** [comment]
Will be supported in 1.6.1
