### ISSUE TITLE
Can't place modded laterns, if this mod is active

### ISSUE THREAD

**Issue by Cape-City** [ThePoultryMan/Lanterns-Belong-On-Walls#17]
Hi,

i'm using 1.19.3 on fabric and when this mod is active, i can't place modded laterns or lamps anymore.
Not hanging from top or on the ground. The following Mods with laterns and lamps i use so far:

- Skinned Lanterns
- Beautify
- Macaw's Lights and Lamps

It would be perfect, if they also can place on walls, but placing them like standard would be nice again ;)

Even a blacklist, which laterns or lamps this mod should ignore would be fine too, if implementing is not possible.

**Comment by ThePoultryMan** [comment]
I'll play around and see if there is a fix for not being able to place modded lanterns. Support for the mods would fix this issue, but that doesn't solve the underlying problem.

**Comment by ThePoultryMan** [comment]
This is fixed as of 1.6.0, unreleased at the time of writing.

**Comment by Cape-City** [comment]
It's a pity that the fix doesn't come out for 1.19.3 as well. In my modpack there are still so many mods, which do not run cleanly under 1.19.4 or higher, that it will take quite a while until I can finally update.
