### ISSUE TITLE
Backport the 1.5.0 fixes to 1.19.2

### ISSUE THREAD

**Issue by jozzo402** [ThePoultryMan/Lanterns-Belong-On-Walls#18]
Specifically looking for this fix to be backported:
> One large issue this fixes is spawning with the wrong blockstate, meaning all lanterns should look like have been properly been placed down when generating naturally.

A lot of mods are still on 1.19.2 so I'm forced to continue using 1.4.0, would love to get rid of the jankily-placed lanterns that generate on structures.

**Comment by ThePoultryMan** [comment]
1.20.4 is the only currently supported version. This issue is no longer relevant.
