### ISSUE TITLE
Generated hanging lanterns generate with invalid facing state

### ISSUE THREAD

**Issue by P0stf1x** [ThePoultryMan/Lanterns-Belong-On-Walls#21]
**Describe the bug**
Hanging lanterns in ancient cities (and possibly other structures) generate with `facing: up` state, instead of `facing: down`

**Reproduction Steps**
1. Install mod
2. Create new world
3. Go to ancient city
4. Find soul lantern

**Expected behavior**
Hanging lanterns (with state `hanging: true`) should also generate with `facing: down` state

**Screenshots**
![2024-02-03_20 40 05](https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/assets/46126263/58bee5b1-7a8a-4c1c-a257-1a890321858a)

**Mod Information:**
 - Minecraft Version: 1.20.1
 - Loader Version: 0.15.6
 - Mod Version: 1.6.1+1.20.1

**Comment by ThePoultryMan** [comment]
Fixed as of 1.7.0
