### ISSUE TITLE
Support for Latest Versions of Minecraft

### ISSUE THREAD

**Issue by realguyman** [ThePoultryMan/Lanterns-Belong-On-Walls#24]
Hello! I'm wondering if you're planning on maintaining this project? The last version release was for 1.20.4, and now Minecraft is at 1.21.3. If you're not planning on maintaining the project, I'd like to fork this.

**Comment by ThePoultryMan** [comment]
I am working on support for newer versions, but due to moving away from [Statement](https://modrinth.com/mod/statement) it is taking longer than expected.

**Comment by realguyman** [comment]
Ah, OK. Sweet! Thank you!
