### ISSUE TITLE
in my game for some reason it doesn't want to work

### ISSUE THREAD

**Issue by heeroyuy180** [ThePoultryMan/Lanterns-Belong-On-Walls#3]
in my game for some reason it doesn't want to work
 I am using these resource packs https://www.curseforge.com/minecraft/texture-packs/two-thousand-leagues-256x
https://youtu.be/5bUkW4VL8So
no error appears or anything, it just won't put :/
PS: yes, I already tried disabling the resource pack.
EliotXII here.

**Comment by ThePoultryMan** [comment]
Do you know how to find the logs? They would be quite helpful in this case.

**Comment by heeroyuy180** [comment]
which one?

**Comment by ThePoultryMan** [comment]
The one called `latest.log`. It will be the newest file.

**Comment by heeroyuy180** [comment]
[latest.log](https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/files/8691075/latest.log)

**Comment by ThePoultryMan** [comment]
You're using forge, but this mod is only available for the Fabric or Quilt mod loader.

**Comment by heeroyuy180** [comment]
now I understand
in the curse this was not specified
sorry for bothering
