### ISSUE TITLE
Crash when attempting to place lanterns on empty sides of slabs

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [ThePoultryMan/Lanterns-Belong-On-Walls#4]
**Describe the bug:**

When you right-click a top slab from below, while holding a lantern, the game crashes.
If you place the lantern on top of a bottom slab, the game will also crash.

**Reproduction Steps:**

1. Place a top slab anywhere you want, make sure there are no full blocks next to it, so that the lantern doesn't attach to it
2. Aim at the slab from below and try to place a lantern
3. Crash

or

1. Place a bottom slab
2. Try to place a lantern on top of it
3. Crash

If you don't make sure that there are no full blocks next to the slab, the lantern will simply attach to them instead.

**Expected behavior:**

The game should completely ignore any attempts to place lanterns on non-full blocks. 

**Mod Information:**
 - Minecraft Version: 1.18.2
 - Loader Version: 0.14.4
 - Mod Version: 1.1.0

**Logs:**

https://gist.github.com/Footage2-Amply-Pounce/9cc3d1a8d6f617362516cf26ef617e98

**Comment by ThePoultryMan** [comment]
This happens because I'm using `direction` instead of `horizontal direction`. I'll fix this in 1.2.0.
