### ISSUE TITLE
generated lanterns on top of block have wall-texture

### ISSUE THREAD

**Issue by mmmmmabil** [ThePoultryMan/Lanterns-Belong-On-Walls#9]
**Describe the bug**
when visiting a ancient city i saw lanterns that were on top of blocks but had the texture as if they were on a wall
the 

**Reproduction Steps**
Example:
1. install mod 
2. tp to an ancient city which has lanterns
3. mine and place one to get the right blockstate

**Expected behavior**
lanterns placed look like in vanilla without the conection to the wall

**Screenshots**
![2022-09-11_18 20 19](https://user-images.githubusercontent.com/95183826/189538758-7e72d203-8fe3-411b-8721-12c531cadc3a.png)

**Mod Information:**
 - Minecraft Version:  1.19.2
 - Loader Version: fabric 14.9 on client and server
 - Mod Version: 1.4.0

**Comment by mmmmmabil** [comment]
made a mistake 
they generate as the one that is supposed to be on walls 
meaning if you update them without providing a support on the side where they should connect they pop off

**Comment by ThePoultryMan** [comment]
Do they all generate like this, or do some generate normally? I’m asking because the one to the left, in your image, appears to be normal.

**Comment by mmmmmabil** [comment]
oh yeah my bad should said that the one that is on the left was mined and placed down

**Comment by ThePoultryMan** [comment]
If you can, do you mind sending me a F3 screenshot of a lantern that is trying generate hanging?

**Comment by mmmmmabil** [comment]
![2022-09-14_23 01 26](https://user-images.githubusercontent.com/95183826/190261919-4fa3ee9b-1328-4e0b-a64e-56a6412c79da.png)
smth like this?

**Comment by ThePoultryMan** [comment]
Yes, that's exactly what I was looking for. I might be able to fix this by overriding Minecraft's structures, but I'd like to avoid that because it could cause conflicts with other mods.
I'll continue to look into ways of fixing this.

**Comment by ThePoultryMan** [comment]
Now that the mod is using Statement, this should be fixed. Although, I will test that before closing this issue.

**Comment by ThePoultryMan** [comment]
Fixed in 1.6.0
